# Factorizacion de matrices

Basado en los comandos descritos en [Numpy.linalg](https://numpy.org/doc/stable/reference/routines.linalg.html)

## 1. Descomposición LU



Para esta descomposicion usaremos la libreria Scipy.

In [1]:
from scipy.linalg import lu
import numpy as np

El comando lu de Scipy nos retorna $\mathbf{PA}=\mathbf{LU}$

In [2]:
A = np.array([[2,4,-1,5,-2],[-4,-5,3,-8,1],[2,-5,-4,1,8],[-6,0,7,-3,1]])
P, L, U = lu(A)
print(P)
print(L)
print(U)
print(P@(L@U))

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [-0.33333333  1.          1.          0.        ]
 [-0.33333333 -0.8        -0.          1.        ]]
[[-6.00000000e+00  0.00000000e+00  7.00000000e+00 -3.00000000e+00
   1.00000000e+00]
 [ 0.00000000e+00 -5.00000000e+00 -1.66666667e+00 -6.00000000e+00
   3.33333333e-01]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16  6.00000000e+00
   8.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -8.00000000e-01
  -1.40000000e+00]]
[[ 2.  4. -1.  5. -2.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [-6.  0.  7. -3.  1.]]


In [3]:
print(P@A)
print(L@U)

[[-6.  0.  7. -3.  1.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [ 2.  4. -1.  5. -2.]]
[[-6.  0.  7. -3.  1.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [ 2.  4. -1.  5. -2.]]


Solucion de sistemas de ecuacion con LU, $\mathbf{A}\mathbf{x}=\mathbf{b}$, con <br>
$$ \mathbf{A} = \begin{bmatrix} 3 & 7 & -2\\ -3 & 5 & 1\\ 6 & -4 & 0 \end{bmatrix} \quad \mathbf{b} = \begin{bmatrix} -7\\ 5\\ 2 \end{bmatrix}$$

In [4]:
A = np.array([[3,7,-2],[-3,5,1],[6,-4,0]])
b = np.array([[-7],[5],[2]])

Recordar que $\mathbf{PA}=\mathbf{LU}$, entonces $\mathbf{LU}\mathbf{x}=\mathbf{Pb}$

In [5]:
P,L,U = lu(A)

La solucion es $\mathbf{x}=\mathbf{U}^{-1}\mathbf{L}^{-1}\mathbf{P}\mathbf{b}$

In [6]:
x = np.linalg.solve(U,np.linalg.solve(L,P@b))
print(x)

[[ 0.41111111]
 [-0.63333333]
 [-2.6       ]]


In [7]:
print(P@(A@x))
print(b)

[[-7.]
 [ 5.]
 [ 2.]]
[[-7]
 [ 5]
 [ 2]]


## 2. Descomposicion QR

Aqui hacemos uso de la funcion qr dentron de la sub-libreria linalg de Numpy.

In [8]:
A = np.array([[1,0,0],[1,1,0],[1,1,1],[1,1,1]])
print(A)

[[1 0 0]
 [1 1 0]
 [1 1 1]
 [1 1 1]]


In [9]:
Q,R = np.linalg.qr(A)
print(Q)
print(R)

[[-0.5         0.8660254   0.        ]
 [-0.5        -0.28867513  0.81649658]
 [-0.5        -0.28867513 -0.40824829]
 [-0.5        -0.28867513 -0.40824829]]
[[-2.         -1.5        -1.        ]
 [ 0.         -0.8660254  -0.57735027]
 [ 0.          0.         -0.81649658]]


In [10]:
Q.T@Q

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 6.34802232e-18],
       [0.00000000e+00, 6.34802232e-18, 1.00000000e+00]])

## 3. Descomposición en valores singulares

Para este caso usamos el comando svd en la sub-libreria linalg de Numpy.

In [11]:
A = np.array([[3,7,-2],[-3,5,1],[6,-4,0]])
b = np.array([[-7],[5],[2]])
U,S,V = np.linalg.svd(A)
print(U)
print(S)
print(V)

[[ 0.55502967 -0.8007784  -0.22515775]
 [ 0.57599594  0.17469387  0.79856792]
 [-0.60014226 -0.57291885  0.55820539]]
[9.88531219 7.0434192  1.29261319]
[[-0.37062587  0.92720961 -0.05402595]
 [-0.90352849 -0.34646583  0.25218585]
 [ 0.215111    0.14228059  0.96616949]]


In [12]:
S.shape

(3,)

In [13]:
print(U.T@U)
print(V.T@V)
print(np.prod(S))
print(np.linalg.det(A))

[[ 1.00000000e+00  1.02746507e-16  6.44359149e-17]
 [ 1.02746507e-16  1.00000000e+00 -3.09020167e-17]
 [ 6.44359149e-17 -3.09020167e-17  1.00000000e+00]]
[[ 1.00000000e+00 -1.80804591e-16 -6.78657194e-17]
 [-1.80804591e-16  1.00000000e+00 -5.46329321e-17]
 [-6.78657194e-17 -5.46329321e-17  1.00000000e+00]]
89.99999999999997
90.0


In [14]:
np.diag(S)

array([[9.88531219, 0.        , 0.        ],
       [0.        , 7.0434192 , 0.        ],
       [0.        , 0.        , 1.29261319]])

In [15]:
print(U@np.diag(S)@V)
print(A)

[[ 3.00000000e+00  7.00000000e+00 -2.00000000e+00]
 [-3.00000000e+00  5.00000000e+00  1.00000000e+00]
 [ 6.00000000e+00 -4.00000000e+00  7.97392342e-16]]
[[ 3  7 -2]
 [-3  5  1]
 [ 6 -4  0]]


Si $\mathbf{A}\mathbf{x}=\mathbf{b}$ entonces $\mathbf{USV}^{\top}\mathbf{x}=\mathbf{b}$, entonces $\mathbf{x}=\mathbf{VS}^{-1}\mathbf{U}^{\top}\mathbf{b}$

In [16]:
x = V.T@np.diag(1/S)@U.T@b
print(x)

[[0.51111111]
 [0.26666667]
 [5.2       ]]


In [17]:
print(A@x)
print(b)

[[-7.]
 [ 5.]
 [ 2.]]
[[-7]
 [ 5]
 [ 2]]


## 4. Pseudo inversas

Para matrices rectangulares $\mathbf{A}$, la pseudo inversa es $\mathbf{A}^{\dagger}=(\mathbf{A^{\top}}\mathbf{A})^{-1}\mathbf{A}^{\top}$.

In [18]:
A1 = np.array([[2,4,-1,5,-2],[-4,-5,3,-8,1],[2,-5,-4,1,8],[-6,0,7,-3,1]])
A2 = np.array([[1,0,0],[1,1,0],[1,1,1],[1,1,1]])
print(A1.shape,A2.shape)

(4, 5) (4, 3)


In [19]:
A1pinv = np.linalg.pinv(A1)
A2pinv = np.linalg.pinv(A2)

In [20]:
print(A1@A1pinv)

[[ 1.00000000e+00 -8.88178420e-16 -2.22044605e-16  5.55111512e-17]
 [ 1.24344979e-14  1.00000000e+00  2.22044605e-16 -1.66533454e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00 -6.66133815e-16]
 [ 9.76996262e-15  6.21724894e-15  2.22044605e-15  1.00000000e+00]]


In [21]:
print(A2pinv@A2)

[[ 1.00000000e+00 -5.07190585e-16 -7.54909981e-17]
 [ 3.69293411e-16  1.00000000e+00  1.47248807e-16]
 [-1.66533454e-16 -3.88578059e-16  1.00000000e+00]]
